<?php

/**
 * Default system settings.
 * 
 * SOP App Color Scheme:
 *   Primary: Deep navy for professional appearance
 *   Department (Shelf): Steel blue
 *   Knowledge Domain (Book): Teal green
 *   SOP Group (Chapter): Amber/gold
 *   SOP Document (Page): Navy blue
 *   Draft: Purple (indicates pending work)
 *
 * Changes to these config files are not supported by BookStack and may break upon updates.
 * Configuration should be altered via the `.env` file or environment variables.
 * Do not edit this file unless you're happy to maintain any changes yourself.
 */

return [

    'app-name'             => 'SOP Manager',
    'app-logo'             => '',
    'app-name-header'      => true,
    'app-editor'           => 'wysiwyg',
    // Light mode colors
    'app-color'            => '#1e3a5f',  // Deep navy - professional primary
    'app-color-light'      => 'rgba(30,58,95,0.12)',
    'link-color'           => '#2563eb',  // Bright blue for links
    'bookshelf-color'      => '#475569',  // Steel/slate - Departments
    'book-color'           => '#0d9488',  // Teal - Knowledge Domains
    'chapter-color'        => '#d97706',  // Amber - SOP Groups
    'page-color'           => '#1e40af',  // Deep blue - SOP Documents
    'page-draft-color'     => '#7c3aed',  // Purple - Drafts (pending)
    // Dark mode colors
    'app-color-dark'       => '#1e3a5f',
    'app-color-light-dark' => 'rgba(30,58,95,0.20)',
    'link-color-dark'      => '#60a5fa',  // Lighter blue for dark mode
    'bookshelf-color-dark' => '#94a3b8',  // Lighter slate - Departments
    'book-color-dark'      => '#2dd4bf',  // Lighter teal - Knowledge Domains  
    'chapter-color-dark'   => '#fbbf24',  // Lighter amber - SOP Groups
    'page-color-dark'      => '#60a5fa',  // Lighter blue - SOP Documents
    'page-draft-color-dark' => '#a78bfa', // Lighter purple - Drafts
    'app-custom-head'      => false,
    'registration-enabled' => false,

    // User-level default settings
    'user' => [
        'ui-shortcuts'          => '{}',
        'ui-shortcuts-enabled'  => false,
        'dark-mode-enabled'     => env('APP_DEFAULT_DARK_MODE', false),
        'bookshelves_view_type' => env('APP_VIEWS_BOOKSHELVES', 'grid'),
        'bookshelf_view_type'   => env('APP_VIEWS_BOOKSHELF', 'grid'),
        'books_view_type'       => env('APP_VIEWS_BOOKS', 'grid'),
    ],

];
